# PUSHGATEWAY:
  PGW HOST: 10.210.110.32
  PGW PORT: 9091

# KAFKA
  BOOTSTRAP SERVER: 10.210.150.164:9092
  TOPIC: Die_Zukunft
  GROUP ID: my-group
  KEY: ZUKUNFT

# METRICS
  METRIC NAME: zukunft
  JOB NAME: zukunft_test
  LABEL NAME: instance
  LABEL VALUE: zukunft_instance
