# https://towardsdatascience.com/from-novice-to-expert-how-to-write-a-configuration-file-in-python-273e171a8eb3

# PUSHGATEWAY:
  PGW HOST: 10.210.110.32
  PGW PORT: 9091
  JOB NAME: demo_pg_job
  LABEL NAME: instance
  LABEL VALUE: demo_instance

# KAFKA
  KAFKA: 10.210.110.20
  TOPIC PORT: 9092
  TOPIC: m-exp
  KEY: TEST

# METRICS
  METRIC NAME: demo_metric
  METRIC VALUE: 123