# https://towardsdatascience.com/from-novice-to-expert-how-to-write-a-configuration-file-in-python-273e171a8eb3

# PUSHGATEWAY:
  PGW HOST: 192.168.192.2
  PGW PORT: 8080
  JOB NAME: demo_pg_job
  LABEL NAME: instance
  LABEL VALUE: demo_instance

# KAFKA
  KAFKA: 10.0.0.10
  TOPIC PORT: 9020
  TOPIC: TEST
  KEY: TEST

# METRICS
  METRIC NAME: demo_metric
  METRIC VALUE: 123