# PUSHGATEWAY:
  PGW HOST: 10.210.110.32
  PGW PORT: 9091

# KAFKA
  BOOTSTRAP SERVER: 10.210.110.20:9092
  TOPIC: m-exp
  GROUP ID: my-group
  KEY: TEST

# METRICS
  METRIC NAME: demo_metric
  JOB NAME: demo_pg_job
  LABEL NAME: instance
  LABEL VALUE: demo_instance