apiVersion: apps/v1
kind: Deployment
metadata:
  name: m-exp
  namespace: zukunft
  labels:
    name: m-exp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m-exp
  template:
    metadata:
      name: m-exp
      labels:
        name: m-exp
    spec:
      volumes:
       - name: config-volume
         configMap:
          name: m-exp-config
      containers:
        - name: exporter
          image: zukunft/metrics_exporter:1.5.08
#          imagePullPolicy: Always
          volumeMounts:
          - name: config-volume
            subPath: config.yaml
            mountPath: "/config/config.yaml"
      dnsPolicy: ClusterFirstWithHostNet