apiVersion: v1
kind: Service
metadata:
  name: m-exp
  namespace: default
  labels:
    name: m-exp
spec:
  type: LoadBalancer
#  loadBalancerIP: 10.10.10.10
  ports:
    - port: 8080
      targetPort: 8080
      name: m-exp
    - port: 8090
      targetPort: 8090
      name: m-exp2
  selector:
    name: m-exp