apiVersion: v1
kind: Service
metadata:
  name: m-exp
  namespace: zukunft
  labels:
    name: m-exp
spec:
  type: LoadBalancer
  loadBalancerIP: 10.210.110.26
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: m-exp
  selector:
    name: m-exp
